version: '3.8'
services:
  postgres:
    container_name: wanago-postgres
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: 'nestjs'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres
volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
